#!/bin/bash -x

if [[ ${RE_JOB_SCENARIO} == "lint" ]]
then
    gating/pre_merge_test/runLint
    gating/pre_merge_test/runUnit
fi


if [[ ${RE_JOB_SCENARIO} == "unit" ]]
then
    gating/pre_merge_test/runUnit
fi